SportStore/Models/CategoryLink.cs
using System.Web.Routing;

namespace SportStore.Models
{
    public class CategoryLink: NavigationLink
    {
        public CategoryLink(string category)
        {
            Text = category ?? "Home";
            RouteValues =
                new RouteValueDictionary(
                    new {controller = "Product", action = "List", category, pageNumber = 1});
        }
    }
}

SportStore/Models/NavigationLink.cs
using System.Web.Routing;

namespace SportStore.Models
{
    public class NavigationLink
    {
        public bool IsSelected { get; set; }

        public string Text { get; set; }

        public RouteValueDictionary RouteValues { get; set; }
    }
}

SportStore/Models/ProductListViewModel.cs
using System.Collections.Generic;

namespace SportStore.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<DomainModel.DAL.Product> Products { get; set; }

        public int CurrentPage { get; set; }

        public string CurrentCategory { get; set; }

        public int TotalPagesCount { get; set; }
    }
}

SportStore/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomainModel.Interfaces;
using SportStore.Models;

namespace SportStore.Controllers
{
    public class NavigationController : Controller
    {
        private IProductRepository productRepository;

        public NavigationController(IProductRepository productRepo)
        {
            productRepository = productRepo;
        }

        public ViewResult Menu(string selectedCategory)
        {
            var navLinks = new List<NavigationLink>
                {
                    new CategoryLink(null) {IsSelected = string.IsNullOrEmpty(selectedCategory)}
                };

            var categories = productRepository.Products.Select(x => x.Category).Distinct().OrderBy(x => x);
            foreach (var category in categories)
            {
                navLinks.Add(new CategoryLink(category) {IsSelected = category == selectedCategory});
            }
            ViewData["category"] = selectedCategory;
            return View(navLinks);
        }
    }
}

SportStore/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using DomainModel.Interfaces;
using SportStore.Models;

namespace SportStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository productRepository;
        public int PageSize = 3;

        public ProductController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public ViewResult List(string category, int pageNumber)
        {
            var products =
                productRepository.Products
                .Where(p => string.IsNullOrEmpty(category) || p.Category == category)
                .OrderBy(p => p.Name)
                .Skip(PageSize * (pageNumber - 1))
                .Take(PageSize).ToList();

            var productsCount = productRepository.Products.Count(p => string.IsNullOrEmpty(category) || p.Category == category);
            var totalPagesCount = (int)Math.Ceiling((double)productsCount / PageSize);

            var viewModel = new ProductListViewModel
                {
                    Products = products,
                    CurrentPage = pageNumber,
                    TotalPagesCount = totalPagesCount,
                    CurrentCategory = category
                };

            return View(viewModel);
        }

    }
}

SportStore/Views/Navigation/Menu.cshtml
@model IEnumerable<SportStore.Models.NavigationLink>

@foreach (var link in Model)
{
    <a href="@Url.RouteUrl(link.RouteValues)" class="@(link.IsSelected? "selected": "")">@link.Text</a>
}

SportStore/Views/Product/List.cshtml
@using SportStore.HtmlHelpers;
@model SportStore.Models.ProductListViewModel

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

@foreach (var product in Model.Products)
{
    Html.RenderPartial("ProductSummary", product);
}
<div class="pager">
    Page: @Html.PagingLinks(Model.CurrentPage, Model.TotalPagesCount, x =>Url.Action("List", new {category = Model.CurrentCategory, pageNumber = x}))
</div>

SportStore/Views/Shared/ProductSummary.cshtml
@model DomainModel.DAL.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description
    <h4>@Model.Price.ToString("c")</h4>
</div>

SportStore/Views/Shared/_Layout.cshtml
@model SportStore.Models.ProductListViewModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/Styles/styles.css"/>
    <title>@ViewBag.Title</title>
</head>
    <body>
        <div id="header">
            <div class="title">SPORTS STORE  <span class="subtitle">@(string.IsNullOrEmpty(Model.CurrentCategory)? "" : Model.CurrentCategory)</span></div>
        </div>
        <div id="categories">
            @{ Html.RenderAction("Menu", "Navigation", new { selectedCategory = Model.CurrentCategory });}
        </div>
        <div id="content">
            @RenderBody()
        </div>
    </body>
</html>